### ISSUE TITLE
the mod keeps on saying it needs fabric api even though i have it installed

### ISSUE THREAD

**Issue by memz100** [Hibiii/Blahaj#14] opened 2023-06-24 00:07 UTC

**Comment by hibiii** [comment] 2023-06-24 00:10
What minecraft version?

**Comment by hibiii** [comment] 2023-06-24 00:31
I've tried it against the 4 Minecraft versions Blåhaj supports, I could not reproduce. If possible, upload a crash log.

Closing as cannot reproduce.

**Closed as not planned by hibiii** 2023-06-24 00:31 UTC
Labels: cannot reproduce
